import type { Template } from './types';

export const TEMPLATES: Template[] = [
  {
    id: 'landing-saas',
    title: 'SaaS Landing Page',
    description: 'Modern landing page template for SaaS products with hero, features, pricing, and testimonials sections.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
    previewUrl: 'https://example.com/preview/saas',
    previewImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=800&fit=crop',
    author: 'Apsara Digital',
    category: 'Landing Page',
    tags: ['SaaS', 'Marketing', 'React'],
    downloadUrl: '/assets/templates/saas-landing.zip',
    fileSize: '2.4 MB',
    license: 'free',
  },
  {
    id: 'portfolio-minimal',
    title: 'Minimal Portfolio',
    description: 'Clean and minimal portfolio template perfect for designers and developers.',
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop',
    previewImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=800&fit=crop',
    author: 'Apsara Digital',
    category: 'Portfolio',
    tags: ['Portfolio', 'Minimal', 'Personal'],
    downloadUrl: '/assets/templates/portfolio-minimal.zip',
    fileSize: '1.8 MB',
    license: 'free',
  },
  {
    id: 'ecommerce-starter',
    title: 'E-Commerce Starter',
    description: 'Full-featured e-commerce template with product grid, cart, and checkout pages.',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop',
    previewImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&h=800&fit=crop',
    author: 'Apsara Digital',
    category: 'E-Commerce',
    tags: ['Shop', 'E-Commerce', 'Next.js'],
    downloadUrl: '/assets/templates/ecommerce-starter.zip',
    fileSize: '4.2 MB',
    license: 'premium',
  },
  {
    id: 'blog-modern',
    title: 'Modern Blog',
    description: 'Beautiful blog template with MDX support, categories, and search functionality.',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400&h=300&fit=crop',
    previewImage: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=1200&h=800&fit=crop',
    author: 'Apsara Digital',
    category: 'Blog',
    tags: ['Blog', 'MDX', 'Content'],
    downloadUrl: '/assets/templates/blog-modern.zip',
    fileSize: '1.5 MB',
    license: 'free',
  },
  {
    id: 'dashboard-admin',
    title: 'Admin Dashboard',
    description: 'Comprehensive admin dashboard with charts, tables, and user management.',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop',
    previewImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=800&fit=crop',
    author: 'Apsara Digital',
    category: 'Dashboard',
    tags: ['Admin', 'Dashboard', 'Analytics'],
    downloadUrl: '/assets/templates/dashboard-admin.zip',
    fileSize: '5.1 MB',
    license: 'commercial',
  },
];
