nodeLinker: node-modules

enableGlobalCache: false

nmHoistingLimits: workspaces

packageExtensions:
  "@emoji-mart/react@*":
    peerDependencies:
      react: "*"
  "@radix-ui/react-tabs@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
