enableGlobalCache: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

packageExtensions:
  "@emoji-mart/react@*":
    peerDependencies:
      react: "*"
  "@radix-ui/react-tabs@*":
    peerDependencies:
      react: "*"
      react-dom: "*"

yarnPath: .yarn/releases/yarn-4.7.0.cjs
