/**
 * useVibeEditorConvex Hook
 *
 * Main hook for the Vibe Code Editor that manages:
 * - Chat messages (fetching from Convex, displaying, sending)
 * - Streaming responses from the AI coding agent
 * - File artifacts generated by the agent
 *
 * Data Flow:
 * 1. User sends message → handleSendMessage()
 * 2. Message saved to Convex → streamFromAgent() starts
 * 3. SSE stream received → callbacks update UI state in real-time
 *    - text-delta events are saved to Convex progressively (debounced)
 * 4. Stream completes → final content saved to Convex (message + artifacts)
 * 5. Convex query auto-updates → UI shows persisted messages
 */

// Re-export from modular structure for backward compatibility
export { useVibeEditorConvex } from './vibe-editor';
export type {
  ActivityLogEntry,
  PendingMessage,
  TransformedMessage,
  StreamingState,
  UseVibeEditorReturn,
} from './vibe-editor';
